# DigitalOcean App Platform Configuration
# This file configures your app for deployment on DigitalOcean App Platform

name: disasterlens
services:
- name: web
  source_dir: /
  github:
    repo: UMBC-Hackathon  # Replace with your actual repo name
    branch: main
    deploy_on_push: true
  run_command: npm start
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: NEXT_PUBLIC_SUPABASE_URL
    value: ${NEXT_PUBLIC_SUPABASE_URL}
  - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
    value: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
  - key: SUPABASE_SERVICE_ROLE_KEY
    value: ${SUPABASE_SERVICE_ROLE_KEY}
  - key: GEMINI_API_KEY
    value: ${GEMINI_API_KEY}
  - key: NEXT_PUBLIC_APP_URL
    value: ${APP_URL}